"""AI Travel Planner - Main Entry Point.

This is the new AI-centric version that:
1. Asks for API key securely (not stored in files)
2. Uses AI to guide the entire planning process
3. No mock data - everything generated by AI
4. Natural conversation flow
"""

from src.presentation.cli.ai_travel_cli import main

if __name__ == "__main__":
    main()
